anchors:
  - &targetDefaults
    replicaCount: 1
    slowloris:
      enabled: false
      https: true
      resources: {}
    ddosify:
      enabled: true
      protocol: HTTPS
      resources:
        limits:
          cpu: 10m
          memory: 10Mi
        requests:
          cpu: 5m
          memory: 5Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

targets:
  example:
    <<: *targetDefaults
    replicaCount: 20
    host: example.com
    port: 443
